apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kibana-cluster1-cert
  namespace: cluster1
spec:
  commonName: kibana-cluster1.hela.hack2022.ch
  dnsNames:
  - kibana-cluster1.hela.hack2022.ch
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt
  secretName: kibana-cluster1-tls

