apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: logstash-dump-exe-cluster2
  namespace: argocd 
spec:
  generators:
  - git:
      repoURL: https://github.com/beninim/ECK-cscs.git
      revision: HEAD 
      files:
      - path: 'logstash2/dump-exe.yaml'
  template:
    metadata:
      name: logstash-dump-exe-cluster2
    spec:
      project: default
      source:
        helm:
          values: |-
            {{values}}
        repoURL: https://helm.elastic.co
        targetRevision: 8.5.0
        chart: logstash
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: cluster2
      syncPolicy:
        automated:
          selfHeal: true
          prune: false 