apiVersion: v1
kind: Secret
metadata:
  name: elastic-credentials-cluster2
  namespace: cluster2
type: Opaque
data:
  ELASTICSEARCH_USERNAME: ZWxhc3RpYwo=
  ELASTICSEARCH_PASSWORD: NmdXMEFXMGQxcDkyQzF3QzdWWU0zRTVx